//
//  ALStyleKit.h
//  ALYandexSpeller
//
//  Created by Andrey on 14.10.15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ALStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* nextImageRawTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* prevImageRawTargets;

// Colors
+ (UIColor*)yandexColor;
+ (UIColor*)yandexColorLight;

// Drawing Methods
+ (void)drawCorrectImageRaw;

// Generated Images
+ (UIImage*)imageOfNextImageRaw;
+ (UIImage*)imageOfNextImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPrevImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPrevImageRaw;
+ (UIImage*)imageOfCorrectImageWithFrame: (CGRect)frame;

@end
